const INLIER_THRESHOLD = 3;
//const MIN_NUM_INLIERS = 8;  //default
const MIN_NUM_INLIERS = 6;
const CLUSTER_MAX_POP = 8;
const HAMMING_THRESHOLD = 0.7;

const CAUCHY_SCALE = 0.01;
const CHUNK_SIZE = 10;
const NUM_HYPOTHESES = 20;
const NUM_HYPOTHESES_QUICK = 10;

export {
  INLIER_THRESHOLD,
  MIN_NUM_INLIERS,
  CLUSTER_MAX_POP,
  HAMMING_THRESHOLD,
  CAUCHY_SCALE,
  CHUNK_SIZE,
  NUM_HYPOTHESES,
  NUM_HYPOTHESES_QUICK,
};
